### ISSUE TITLE
Next Release Date?

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_fix#3]
When is the next release planned? Currently there are some features only available on the *develop* branch. This situation did not change since December. 

I would like to use some of the new FIR filters, so it would be nice doing so from a proper release instead of the *develop* branch.

**Comment by rybaniec-r** [comment]
There is a chance to have the new release this week, if I will be able to find a time slot for doing it.

**Comment by rybaniec-r** [comment]
Version 2.4.1 released.
